/** StayEasy "Warm Modern Hospitality" design system */
module.exports = {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        'secondary-container': '#fd7549',
        'surface-variant': '#e5e2df',
        outline: '#6f7a74',
        'on-primary': '#ffffff',
        'on-error': '#ffffff',
        'outline-variant': '#bec9c3',
        'on-secondary-fixed-variant': '#852400',
        'surface-dim': '#dcdad6',
        'surface-container': '#f0edea',
        'surface-tint': '#086b53',
        'primary-container': '#0f6e56',
        'surface-bright': '#fcf9f5',
        'tertiary-fixed-dim': '#b7cbc4',
        'inverse-primary': '#84d6b9',
        'on-tertiary-fixed': '#0d1f1b',
        error: '#ba1a1a',
        'surface-container-lowest': '#ffffff',
        'on-background': '#1b1c1a',
        'on-secondary-fixed': '#3a0b00',
        'secondary-fixed-dim': '#ffb59e',
        'on-primary-fixed': '#002117',
        'on-surface': '#1b1c1a',
        'tertiary-fixed': '#d3e7e0',
        tertiary: '#3b4d48',
        background: '#fcf9f5',
        'on-tertiary-container': '#cee1db',
        'on-error-container': '#93000a',
        'inverse-surface': '#30302e',
        'surface-container-high': '#eae8e4',
        'primary-fixed': '#a0f3d4',
        'on-tertiary': '#ffffff',
        'secondary-fixed': '#ffdbd0',
        'primary-fixed-dim': '#84d6b9',
        'tertiary-container': '#536560',
        'on-tertiary-fixed-variant': '#394a45',
        secondary: '#a8380f',
        'on-primary-fixed-variant': '#00513e',
        surface: '#fcf9f5',
        'on-surface-variant': '#3f4944',
        'on-primary-container': '#9aedcf',
        'surface-container-highest': '#e5e2df',
        'inverse-on-surface': '#f3f0ed',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#661a00',
        'surface-container-low': '#f6f3f0',
        primary: '#005440',
        'error-container': '#ffdad6',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'space-xs': '0.5rem',
        'container-max': '1240px',
        'gutter-desktop': '1.5rem',
        'space-xl': '2rem',
        'space-2xl': '3rem',
        'space-sm': '0.75rem',
        'space-2xs': '0.25rem',
        'gutter-mobile': '1rem',
        'space-md': '1rem',
        'space-lg': '1.5rem',
        'space-3xl': '4rem',
      },
      fontFamily: {
        'headline-md': ['"Plus Jakarta Sans"', 'sans-serif'],
        'label-sm': ['Inter', 'sans-serif'],
        'body-sm': ['Inter', 'sans-serif'],
        'title-md': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'price-display': ['"Plus Jakarta Sans"', 'sans-serif'],
        'label-md': ['Inter', 'sans-serif'],
        'display-hero-mobile': ['"Plus Jakarta Sans"', 'sans-serif'],
        'headline-lg': ['"Plus Jakarta Sans"', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'headline-sm': ['"Plus Jakarta Sans"', 'sans-serif'],
        'headline-lg-mobile': ['"Plus Jakarta Sans"', 'sans-serif'],
        'display-hero': ['"Plus Jakarta Sans"', 'sans-serif'],
      },
      fontSize: {
        'headline-md': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'label-sm': ['12px', { lineHeight: '16px', letterSpacing: '0.02em', fontWeight: '600' }],
        'body-sm': ['13px', { lineHeight: '18px', letterSpacing: '0.01em', fontWeight: '400' }],
        'title-md': ['16px', { lineHeight: '24px', letterSpacing: '0em', fontWeight: '600' }],
        'body-md': ['15px', { lineHeight: '22px', letterSpacing: '0em', fontWeight: '400' }],
        'price-display': ['22px', { lineHeight: '28px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '500' }],
        'display-hero-mobile': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.015em', fontWeight: '700' }],
        'body-lg': ['18px', { lineHeight: '28px', letterSpacing: '0em', fontWeight: '400' }],
        'headline-sm': ['20px', { lineHeight: '28px', letterSpacing: '-0.005em', fontWeight: '600' }],
        'headline-lg-mobile': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'display-hero': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
      },
      boxShadow: {
        tier1: '0 1px 3px rgba(44,44,42,0.08), 0 1px 2px rgba(44,44,42,0.05)',
        tier2: '0 4px 12px rgba(44,44,42,0.12), 0 2px 4px rgba(44,44,42,0.08)',
        tier3: '0 12px 32px rgba(44,44,42,0.16), 0 4px 12px rgba(44,44,42,0.1)',
      },
    },
  },
  plugins: [],
};